export type Keigenn = {
  id: number;
  icon: number;
  type: "multiplier" | "absorbed";
  multiplier: { physics: number; magic: number; darkness: number };
  isFriendly: boolean;
  name?: string;
  description?: string;
};
export const keigennData: Keigenn[] = [
  {
    name: "鐵壁",
    description: "減輕所受到的傷害",
    id: 1191,
    icon: 13911,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "盾陣",
    description: "受到攻擊時必定發動格擋",
    id: 1856,
    icon: 12510,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "干預",
    description: "減輕所受到的傷害",
    id: 1174,
    icon: 12511,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "預警",
    description: "減輕所受到的傷害",
    id: 74,
    icon: 10151,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "武裝",
    description: "減輕所受到的傷害",
    id: 1176,
    icon: 12513,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神聖領域",
    description: "除特定攻擊之外其他所有攻擊均無效化",
    id: 82,
    icon: 12504,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "聖光幕簾",
    description: "抵消一定傷害",
    id: 727,
    icon: 12509,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "聖盾陣",
    description: "受到攻擊時必定發動格擋",
    id: 2674,
    icon: 12515,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "騎士的堅守",
    description: "減輕所受到的傷害",
    id: 2675,
    icon: 12516,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的直覺",
    description: "自身發動戰技命中時可以恢復體力，同時減輕所受到的傷害",
    id: 735,
    icon: 12555,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "戰慄",
    description: "體力最大值提高\n習得戰慄效果提高后追加效果：自身所受的治療效果提高",
    id: 87,
    icon: 10254,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "復仇",
    description: "受到物理攻擊時會發動反擊",
    id: 89,
    icon: 10256,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "擺脫",
    description: "抵消一定傷害",
    id: 1457,
    icon: 12557,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "死鬥",
    description: "除特定攻擊之外其他所有對自身發動的攻擊均無法令體力減少到1以下",
    id: 409,
    icon: 10266,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血氣",
    description: "自身發動戰技命中時可以恢復體力，同時減輕所受到的傷害",
    id: 2678,
    icon: 12562,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血潮",
    description: "減輕所受到的傷害",
    id: 2679,
    icon: 12563,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初的血煙",
    description: "抵消一定傷害",
    id: 2680,
    icon: 12564,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "至黑之夜",
    description: "抵消一定傷害",
    id: 1178,
    icon: 13118,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "棄明投暗",
    description: "減輕所受到的魔法傷害",
    id: 746,
    icon: 13114,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "暗影墻",
    description: "減輕所受到的傷害",
    id: 747,
    icon: 13113,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗黑佈道",
    description: "減輕所受到的魔法傷害",
    id: 1894,
    icon: 13122,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "行屍走肉",
    description: "受到致命傷害時體力減為1，並附加死而不僵狀態\n但是對部分攻擊無效",
    id: 810,
    icon: 13115,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "獻奉",
    description: "減輕所受到的傷害",
    id: 2682,
    icon: 13123,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "石之心",
    description: "減輕所受到的傷害",
    id: 1840,
    icon: 13610,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "殘暴彈",
    description: "抵消一定傷害",
    id: 1898,
    icon: 13614,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "偽裝",
    description: "招架發動率提高，減輕所受到的傷害",
    id: 1832,
    icon: 13602,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "星雲",
    description: "減輕所受到的傷害",
    id: 1834,
    icon: 13604,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "光之心",
    description: "減輕所受到的魔法傷害",
    id: 1839,
    icon: 13609,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "超火流星",
    description: "除特定攻擊之外其他所有攻擊均無效化",
    id: 1836,
    icon: 13606,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "剛玉之心",
    description: "減輕所受到的傷害",
    id: 2683,
    icon: 13615,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "剛玉之清",
    description: "減輕所受到的傷害",
    id: 2684,
    icon: 13616,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "神祝禱",
    description: "抵消一定傷害",
    id: 1218,
    icon: 12632,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "節制",
    description: "減輕所受到的傷害",
    id: 1873,
    icon: 12633,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "水流幕",
    description: "減輕所受到的傷害",
    id: 2708,
    icon: 12638,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "鼓舞",
    description: "抵消一定傷害",
    id: 297,
    icon: 12801,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "激勵",
    description: "抵消一定傷害",
    id: 1918,
    icon: 12814,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "熾天的幕簾",
    description: "抵消一定傷害",
    id: 1917,
    icon: 12848,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "野戰治療陣",
    description: "減輕所受到的傷害",
    id: 299,
    icon: 12803,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "異想的幻光",
    description: "發動治療魔法的治療量提高，且受到魔法攻擊的傷害減少",
    id: 317,
    icon: 12828,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "熾天的幻光",
    description: "發動治療魔法的治療量提高，且受到魔法攻擊的傷害減少",
    id: 1875,
    icon: 12847,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "生命回生法",
    description: "體力最大值提高，同時自身所受體力恢復效果提高",
    id: 2710,
    icon: 12815,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "怒濤之計",
    description: "減輕所受到的傷害",
    id: 2711,
    icon: 12816,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "命運之輪",
    description: "減輕所受到的傷害",
    id: 849,
    icon: 13226,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "天星交錯",
    description: "抵消一定傷害",
    id: 1889,
    icon: 13250,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "擢升",
    description: "減輕所受到的傷害",
    id: 2717,
    icon: 13262,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "中間學派",
    description: "抵消一定傷害",
    id: 1921,
    icon: 13255,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "均衡診斷",
    description: "抵消一定傷害",
    id: 2607,
    icon: 12954,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "齊衡診斷",
    description: "抵消一定傷害",
    id: 2608,
    icon: 12955,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "均衡預後",
    description: "抵消一定傷害",
    id: 2609,
    icon: 12954,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "堅角清汁",
    description: "減輕所受到的傷害",
    id: 2618,
    icon: 12964,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "白牛清汁",
    description: "減輕所受到的傷害",
    id: 2619,
    icon: 12965,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "整體論",
    description: "減輕所受到的傷害",
    id: 3003,
    icon: 12971,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "整體盾",
    description: "抵消一定傷害",
    id: 3365,
    icon: 12972,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "血印",
    description: "輸血狀態消失後消耗血印檔數重新附加輸血狀態，持續時間結束后根據血印剩餘檔數恢復自身體力",
    id: 2642,
    icon: 17585,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "泛血印",
    description: "泛輸血狀態消失後消耗血印檔數重新附加泛輸血狀態，持續時間結束后根據泛血印剩餘檔數恢復自身體力",
    id: 2643,
    icon: 17355,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "心眼",
    description: "下次受到攻擊時所受到的傷害減輕",
    id: 1232,
    icon: 13307,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "金剛極意",
    description: "減輕所受到的一部分傷害",
    id: 1179,
    icon: 12527,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "行吟",
    description: "減輕所受到的傷害",
    id: 1934,
    icon: 12615,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "策動",
    description: "減輕所受到的傷害",
    id: 1951,
    icon: 13021,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "防守之桑巴",
    description: "減輕所受到的傷害",
    id: 1826,
    icon: 13715,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "即興表演結束",
    description: "抵消一定傷害",
    id: 2697,
    icon: 13721,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "殘影",
    description: "抵消一定傷害",
    id: 488,
    icon: 10605,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "魔罩",
    description: "抵消一定傷害",
    id: 168,
    icon: 10456,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守護之光",
    description: "抵消一定傷害",
    id: 2702,
    icon: 12691,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "守護紋",
    description: "抵消一定傷害",
    id: 2597,
    icon: 12934,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "抗死",
    description: "減輕所受到的魔法傷害，同時自身所受體力恢復效果提高",
    id: 2707,
    icon: 13408,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: true,
  },
  {
    name: "雪仇",
    description: "攻擊所造成的傷害降低",
    id: 1193,
    icon: 13901,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "牽制",
    description: "物理攻擊和魔法攻擊所造成的傷害降低",
    id: 1195,
    icon: 13904,
    type: "multiplier",
    multiplier: { physics: 1, magic: 0.5, darkness: 0 },
    isFriendly: false,
  },
  {
    name: "昏亂",
    description: "物理攻擊和魔法攻擊所造成的傷害降低",
    id: 1203,
    icon: 13917,
    type: "multiplier",
    multiplier: { physics: 0.5, magic: 1, darkness: 0 },
    isFriendly: false,
  },
  {
    name: "體力增加",
    description: "體力最大值提高",
    id: 2120,
    icon: 13523,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "腐臭",
    description: "造成的傷害降低",
    id: 1715,
    icon: 13502,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: false,
  },
  {
    name: "智力精神降低",
    description: "智力與精神有所降低",
    id: 2115,
    icon: 13518,
    type: "multiplier",
    multiplier: { physics: 0, magic: 1, darkness: 0 },
    isFriendly: false,
  },
  {
    name: "龍之力",
    description: "受到的傷害降低",
    id: 2500,
    icon: 13539,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "超硬化",
    description: "無法自由活動，但受到攻擊的傷害減少",
    id: 1722,
    icon: 13509,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "玄結界",
    description: "減輕所受到的傷害，受到一定傷害后將附加玄天武水壁狀態",
    id: 2496,
    icon: 13535,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "仙人盾",
    description: "受到的傷害降低",
    id: 2119,
    icon: 13522,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "強力守護",
    description: "令自身所受到的傷害減少，同時會以攻擊力降低為代價提高自身仇恨",
    id: 1719,
    icon: 13506,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "哥佈防御",
    description: "抵消一定傷害",
    id: 2114,
    icon: 13517,
    type: "absorbed",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "銅墻鐵盾",
    description: "減輕所受到的傷害",
    id: 194,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "堅守要塞",
    description: "減輕所受到的傷害",
    id: 195,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "終極堡壘",
    description: "減輕所受到的傷害",
    id: 196,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "原初大地",
    description: "減輕所受到的傷害",
    id: 863,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "暗黑之力",
    description: "減輕所受到的傷害",
    id: 864,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
  {
    name: "靈魂之青",
    description: "減輕所受到的傷害",
    id: 1931,
    icon: 16306,
    type: "multiplier",
    multiplier: { physics: 1, magic: 1, darkness: 1 },
    isFriendly: true,
  },
];
const keigennMap = new Map(keigennData.map((v) => [v.id, v]));
export function getKeigennById(id: number): Keigenn | undefined {
  const res = keigennMap.get(id);
  if (!res) return res;
  return res;
}
export function createIconUrl(icon: number): string {
  if (typeof icon === "number") {
    let head = [..."000000"];
    let iconStr = icon.toString();
    if (iconStr.length > 3) {
      const temp = [...iconStr].slice(0, iconStr.length - 3).concat(..."000");
      head = [...head.slice(0, 6 - temp.length), ...temp];
    }
    let foot = [..."000000"];
    foot = [...foot.slice(0, 6 - iconStr.length), ...iconStr];
    return `${head.join("")}/${foot.join("")}.png`;
  } else {
    return icon;
  }
}
